
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract simpleWallet {
    
    constructor() public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
    }

    modifier checkOwnerAndAccept() {
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
        _;
    }

    function sendWitoutPayComission(address dest, uint128 amount) public view checkOwnerAndAccept{
        dest.transfer(amount, true, 0);
    }

    function sendWitPayComission(address dest, uint128 amount) public view checkOwnerAndAccept{
        dest.transfer(amount, true, 0);
    }

    function sendAllAndDestroyWallet(address dest) public view checkOwnerAndAccept{
        dest.transfer(0, true, 128 + 32);
    }
}
